[game]
title = "Snake Game"
version = "2.0.0"
window_width = 1280
window_height = 720
fps = 60

[difficulty]
[[difficulty.levels]]
level = 1
speed = 8
food_count = 1
obstacles = 0
special_food_chance = 0.1

[[difficulty.levels]]
level = 2
speed = 10
food_count = 2
obstacles = 5
special_food_chance = 0.15

[[difficulty.levels]]
level = 3
speed = 12
food_count = 2
obstacles = 10
special_food_chance = 0.2

[[difficulty.levels]]
level = 4
speed = 14
food_count = 3
obstacles = 15
special_food_chance = 0.25

[[difficulty.levels]]
level = 5
speed = 16
food_count = 3
obstacles = 20
special_food_chance = 0.3

[[difficulty.levels]]
level = 6
speed = 18
food_count = 4
obstacles = 25
special_food_chance = 0.35

[[difficulty.levels]]
level = 7
speed = 20
food_count = 4
obstacles = 30
special_food_chance = 0.4

[[difficulty.levels]]
level = 8
speed = 22
food_count = 5
obstacles = 35
special_food_chance = 0.45

[[difficulty.levels]]
level = 9
speed = 24
food_count = 5
obstacles = 40
special_food_chance = 0.5

[[difficulty.levels]]
level = 10
speed = 26
food_count = 6
obstacles = 50
special_food_chance = 0.6

[graphics]
grid_size = 20
snake_head_color = "#50FF80"
snake_body_color = "#3CCC60"
food_normal_color = "#FF6464"
food_speed_up_color = "#64C8FF"
food_speed_down_color = "#B464FF"
food_ghost_color = "#FFDC64"
background_color = "#0C141E"
obstacle_color = "#505A64"

[audio]
enable_sound = true
enable_music = true
sound_volume = 0.7
music_volume = 0.5

[controls]
up_key = "W"
down_key = "S"
left_key = "A"
right_key = "D"
pause_key = "Space"
restart_key = "R"

[save]
auto_save = true
save_file = "game_save.json"

[user_settings]
difficulty = 8
game_mode = "classic"

[game_modes.classic]
name = "经典模式"
description = "传统贪吃蛇游戏"

[game_modes.maze]
name = "迷宫模式"
description = "带有障碍物的挑战模式"

[game_modes.freestyle]
name = "自由模式"
description = "无边界限制的自由模式"

[game_modes.time_attack]
name = "限时模式"
description = "在限定时间内获得最高分"

[game_modes.survival]
name = "生存模式"
description = "食物会逐渐消失的生存挑战"
